// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Test 1', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Test 1', async function() {
    await driver.get("http://127.0.0.1:5001/index.html")
    await driver.manage().window().setRect({ width: 500, height: 432 })
    await driver.findElement(By.id("num1")).click()
    await driver.findElement(By.id("num1")).click()
    {
      const element = await driver.findElement(By.id("num1"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("num1")).sendKeys("2")
    await driver.findElement(By.id("num2")).click()
    await driver.findElement(By.id("num2")).sendKeys("3")
    await driver.findElement(By.css("button:nth-child(1)")).click()
  })
})
