name: Run tests

on:
  workflow_dispatch:
  
jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    
    container:
      image: node:20
      
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Google Chrome
        run: |
          apt-get update
          apt-get install -y wget curl unzip gnupg
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | tee /etc/apt/sources.list.d/google-chrome.list
          apt-get update
          apt-get install -y google-chrome-stable
          google-chrome --version

      - name: Install ChromeDriver matching Chrome version
        run: |
          CHROME_VERSION=$(google-chrome-stable --version | awk '{print $3}')
          CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION%.*})
          wget -q "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          chmod +x /usr/local/bin/chromedriver
          chromedriver --version

      - name: Start the web server and wait
        run: |
          cd src
          python3 -m http.server 8000 &
          sleep 15  # Increase sleep time to ensure server startup
          curl http://localhost:8000 || echo "Server is not responding!"
          cd ..

      - name: Install test dependencies
        run: |
          cd tests
          npm install
          npx mocha --version || echo "Mocha is missing"
          ls -la node_modules/.bin || echo "No bin directory found"

      - name: Run Selenium tests with Mocha
        run: |
          cd tests
          npx mocha *.js  # Using npx ensures Mocha runs correctly

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: screenshots
          path: screenshots/
