name: Run tests

on:
  workflow_dispatch:
  
jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    
    container:
      image: node:20
      
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Manually Install Google Chrome & ChromeDriver
        run: |
          apt-get update
          apt-get install -y wget curl unzip gnupg
          
          # Add Google Chrome repo
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | tee /etc/apt/sources.list.d/google-chrome.list
          apt-get update
          
          # Install Google Chrome
          apt-get install -y google-chrome-stable
          command -v google-chrome || echo "Google Chrome installation failed!"
          google-chrome --version || echo "Failed to fetch Chrome version!"

          # Fetch the correct ChromeDriver version
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
          CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION%.*})
          wget -q "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          chmod +x /usr/local/bin/chromedriver
          chromedriver --version

      - run: |
            cd src
            python3 -m http.server 8000 &
            sleep 10 &&
            curl http://localhost:8000
            cd ..
      - run: |
            cd tests
            npm install
            npx mocha *.js  # Use npx to run mocha without relying on node_modules/.bin
            
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: screenshots
          path: screenshots/
